import { US, FR, GB, DE, IT, TW, CH, CA, PL, BR, AT, ZA, TR, NL, QA, KE, IN, JM, UZ, SE, AF, ES, DZ, CO, KZ, DO, CN, CG, MA, BG } from 'country-flag-icons/react/3x2';

export const countryFlagMap: { [key: string]: any } = {
  'US': US,
  'United States': US,
  'USA': US,
  'FR': FR,
  'FRA': FR,
  'GB': GB,
  'UK': GB,
  'United Kingdom': GB,
  'DE': DE,
  'Germany': DE,
  'GER': DE,
  'IT': IT,
  'ITA': IT,
  'TW': TW,
  'Taiwan': TW,
  'CH': CH,
  'CA': CA,
  'Canada': CA,
  'CAN': CA,
  'PL': PL,
  'Poland': PL,
  'POL': PL,
  'Brazil': BR,
  'BR': BR,
  'BRA': BR,
  'AT': AT,
  'Austria': AT,
  'AUT': AT,
  'ZA': ZA,
  'South Africa': ZA,
  'TR': TR,
  'TUR': TR,
  'Turkey': TR,
  'NL': NL,
  'Netherlands': NL,
  'NLD': NL,
  'QA': QA,
  'QAT': QA,
  'Qatar': QA,
  'KE': KE,
  'Kenya': KE,
  'IN': IN,
  'India': IN,
  'JM': JM,
  'UZ': UZ,
  'Uzbekistan': UZ,
  'SE': SE,
  'Sweden': SE,
  'AF': AF,
  'ES': ES,
  'Spain': ES,
  'DZ': DZ,
  'CO': CO,
  'Colombia': CO,
  'KZ': KZ,
  'Kazakhstan': KZ,
  'DO': DO,
  'Dominican Republic': DO,
  'China': CN,
  'CG': CG,
  'Congo': CG,
  'MA': MA,
  'Morocco': MA,
  'BG': BG,
  'Bulgaria': BG,
};

export const getCountryFlag = (countryCode: string) => {
  return countryFlagMap[countryCode] || null;
}; 